import { HomemadePrep } from "./types";

/**
 * Common homemade prep samples (English-first), inspired by the
 * foundational preps in Cocktail Codex and modern bar programs.
 */
export function buildSamplePreps(): HomemadePrep[] {
  const now = Date.now();
  let i = 0;
  const mk = (
    name: string,
    nameAlt: string,
    type: string,
    ingredients: string[],
    recipe: string,
    yieldStr: string,
    shelfLife: string,
    storage: string,
    notes = "",
  ): HomemadePrep => ({
    id: `prep-${i}`,
    name,
    nameAlt,
    type,
    ingredients,
    recipe,
    yield: yieldStr,
    shelfLife,
    storage,
    notes,
    builtin: true,
    createdAt: now + i,
    updatedAt: now + i++,
  });

  return [
    mk(
      "Simple Syrup (1:1)",
      "单糖浆(1:1)",
      "syrup",
      ["200g white sugar 白砂糖", "200g hot water 热水"],
      "Stir sugar into hot water until fully dissolved. Cool and bottle.\n将糖倒入热水中搅拌至完全溶解,放凉装瓶。",
      "~300ml",
      "2 weeks refrigerated 冷藏2周",
      "Refrigerate in sealed bottle 密封冷藏",
      "The workhorse sweetener for most cocktails.",
    ),
    mk(
      "Rich Simple Syrup (2:1)",
      "浓糖浆(2:1)",
      "syrup",
      ["400g white sugar 白砂糖", "200g hot water 热水"],
      "Stir sugar into hot water until dissolved. Cool and bottle.\n糖与热水2:1搅拌至溶解,放凉装瓶。",
      "~450ml",
      "1 month refrigerated 冷藏1个月",
      "Refrigerate in sealed bottle 密封冷藏",
      "Use ~2/3 the amount of 1:1 syrup. Longer shelf life.",
    ),
    mk(
      "Honey Syrup (3:1)",
      "蜂蜜糖浆(3:1)",
      "syrup",
      ["300g honey 蜂蜜", "100g warm water 温水"],
      "Whisk honey with warm water until combined. Cool and bottle.\n蜂蜜与温水3:1搅匀,放凉装瓶。",
      "~350ml",
      "1 month refrigerated 冷藏1个月",
      "Refrigerate in sealed bottle 密封冷藏",
      "For Bee's Knees, Gold Rush, Penicillin.",
    ),
    mk(
      "Demerara Syrup (2:1)",
      "德梅拉拉糖浆(2:1)",
      "syrup",
      ["400g demerara sugar 德梅拉拉蔗糖", "200g hot water 热水"],
      "Stir sugar into hot water until dissolved. Cool and bottle.\n蔗糖与热水2:1搅拌溶解,放凉装瓶。",
      "~450ml",
      "1 month refrigerated 冷藏1个月",
      "Refrigerate in sealed bottle 密封冷藏",
      "Adds rich molasses depth — Old Fashioneds, tiki drinks.",
    ),
    mk(
      "Grenadine",
      "红石榴糖浆",
      "syrup",
      [
        "200ml pomegranate juice 石榴汁",
        "200g white sugar 白砂糖",
        "1 tsp pomegranate molasses 石榴糖蜜(可选)",
        "2 drops orange blossom water 橙花水(可选)",
      ],
      "Warm juice gently (do not boil), stir in sugar until dissolved. Add molasses and orange blossom water. Cool and bottle.\n轻微加热石榴汁(不要煮沸),加糖搅拌溶解,加入糖蜜与橙花水,放凉装瓶。",
      "~350ml",
      "2-3 weeks refrigerated 冷藏2-3周",
      "Refrigerate in sealed bottle 密封冷藏",
      "Way better than store-bought. For Jack Rose, Tequila Sunrise.",
    ),
    mk(
      "Orgeat",
      "杏仁糖浆",
      "syrup",
      [
        "200g blanched almonds 去皮杏仁",
        "300ml water 水",
        "300g sugar 糖",
        "15ml brandy or vodka 白兰地或伏特加",
        "1/4 tsp orange blossom water 橙花水",
      ],
      "Toast almonds lightly, blend with water, steep 3h, strain through cheesecloth. Warm the almond milk, dissolve sugar, add brandy & orange blossom water. Bottle.\n杏仁轻烤后与水打碎浸泡3小时,纱布过滤取杏仁奶,加热溶糖,加白兰地与橙花水装瓶。",
      "~500ml",
      "2 weeks refrigerated 冷藏2周",
      "Refrigerate, shake before use 冷藏,用前摇匀",
      "Essential for Mai Tai, Japanese Cocktail, tiki classics.",
    ),
    mk(
      "Ginger Syrup",
      "姜糖浆",
      "syrup",
      ["100g fresh ginger juice 鲜姜汁", "150g white sugar 白砂糖"],
      "Juice fresh ginger (or blend & strain). Whisk with sugar until dissolved, no heat needed.\n鲜姜榨汁(或打碎过滤),与糖搅拌至溶解,无需加热。",
      "~200ml",
      "2 weeks refrigerated 冷藏2周",
      "Refrigerate in sealed bottle 密封冷藏",
      "For Penicillin, Ginger Rogers, homemade ginger ale.",
    ),
    mk(
      "Raspberry Syrup",
      "覆盆子糖浆",
      "syrup",
      ["200g raspberries 覆盆子", "200g sugar 糖", "100ml water 水"],
      "Combine over low heat ~10 min until berries break down. Strain fine, cool, bottle.\n小火煮约10分钟至果肉软烂,细滤后放凉装瓶。",
      "~300ml",
      "2 weeks refrigerated 冷藏2周",
      "Refrigerate in sealed bottle 密封冷藏",
      "For Clover Club, Floradora.",
    ),
    mk(
      "Passion Fruit Syrup",
      "百香果糖浆",
      "syrup",
      ["150g passion fruit pulp 百香果肉", "150g sugar 糖", "50ml water 水"],
      "Warm gently, stir until sugar dissolves, strain seeds if desired. Cool and bottle.\n轻微加热搅拌至糖溶解,可滤籽,放凉装瓶。",
      "~300ml",
      "2 weeks refrigerated 冷藏2周",
      "Refrigerate in sealed bottle 密封冷藏",
      "For Hurricane, Porn Star Martini.",
    ),
    mk(
      "Vanilla Syrup",
      "香草糖浆",
      "syrup",
      ["1 vanilla bean 香草荚", "200g sugar 糖", "200ml water 水"],
      "Split & scrape vanilla bean, simmer with sugar and water 5 min, steep 1h, strain and bottle.\n香草荚剖开刮籽,与糖水小火煮5分钟,浸1小时后过滤装瓶。",
      "~300ml",
      "3 weeks refrigerated 冷藏3周",
      "Refrigerate in sealed bottle 密封冷藏",
      "For espresso martinis and dessert-style drinks.",
    ),
    mk(
      "Cinnamon Syrup",
      "肉桂糖浆",
      "syrup",
      ["4 cinnamon sticks 肉桂棒", "200g demerara sugar 德梅拉拉糖", "200ml water 水"],
      "Crush cinnamon sticks, simmer with sugar & water 5 min, steep 2h, strain and bottle.\n肉桂棒压碎与糖水煮5分钟,浸2小时后过滤装瓶。",
      "~300ml",
      "1 month refrigerated 冷藏1个月",
      "Refrigerate in sealed bottle 密封冷藏",
      "Tiki staple — Jet Pilot, Don's Mix (2:1 grapefruit + cinnamon).",
    ),
    mk(
      "Falernum",
      "法勒南香料糖浆",
      "cordial",
      [
        "8 cloves 丁香",
        "40g fresh ginger 鲜姜",
        "zest of 8 limes 青柠皮",
        "60ml overproof rum 高度朗姆",
        "300ml simple syrup 单糖浆",
        "30ml fresh lime juice 青柠汁",
        "1/4 tsp almond extract 杏仁精(可选)",
      ],
      "Infuse cloves, ginger & lime zest in rum 24h. Strain, mix with syrup, lime juice and almond extract. Rest 1 day.\n丁香、姜、青柠皮浸朗姆24小时,过滤后与糖浆、青柠汁、杏仁精混合,静置1天。",
      "~400ml",
      "1 month refrigerated 冷藏1个月",
      "Refrigerate in sealed bottle 密封冷藏",
      "Key for Corn 'n' Oil, Zombie, Three Dots and a Dash.",
    ),
    mk(
      "Lime Cordial",
      "青柠康迪奥",
      "cordial",
      [
        "zest of 6 limes 青柠皮屑",
        "200ml fresh lime juice 鲜青柠汁",
        "200g sugar 糖",
        "1/2 tsp citric acid 柠檬酸(可选)",
      ],
      "Muddle zest with sugar, rest 1h (oleo). Add lime juice & citric acid, stir until dissolved, fine strain.\n皮屑与糖混合静置1小时出油,加青柠汁与柠檬酸搅拌溶解后细滤。",
      "~350ml",
      "3 weeks refrigerated 冷藏3周",
      "Refrigerate in sealed bottle 密封冷藏",
      "For a proper Gimlet.",
    ),
    mk(
      "Chili-Infused Tequila",
      "辣椒浸渍龙舌兰",
      "infusion",
      ["700ml blanco tequila 银龙舌兰", "2-3 fresh jalapeños 新鲜墨西哥辣椒"],
      "Slice chilies (seeds in for more heat), infuse in tequila 30-60 min, taste every 15 min, strain when spicy enough.\n辣椒切片(留籽更辣)浸入龙舌兰30-60分钟,每15分钟尝味,达到辣度后过滤。",
      "~700ml",
      "3 months+ 常温3个月以上",
      "Cool dark place 阴凉避光",
      "For Spicy Margarita. Infusion speed varies with chili heat.",
    ),
    mk(
      "Earl Grey-Infused Gin",
      "伯爵茶浸渍金酒",
      "infusion",
      ["700ml London dry gin 伦敦干金", "12g Earl Grey tea 伯爵茶叶"],
      "Add loose tea to gin, steep 2h at room temp, strain through fine mesh.\n茶叶入金酒常温浸2小时,细滤。",
      "~700ml",
      "3 months+ 常温3个月以上",
      "Cool dark place 阴凉避光",
      "For Earl Grey MarTEAni. Don't over-steep or it gets tannic.",
    ),
    mk(
      "Saline Solution (20%)",
      "盐溶液(20%)",
      "solution",
      ["20g sea salt 海盐", "80g warm water 温水"],
      "Dissolve salt in warm water, cool and bottle with dropper.\n盐溶于温水,放凉装滴瓶。",
      "~100ml",
      "Indefinite 长期",
      "Room temperature 常温",
      "2-3 drops round out citrus-forward drinks. Codex trick.",
    ),
    mk(
      "Raspberry Shrub",
      "覆盆子果醋饮",
      "shrub",
      ["200g raspberries 覆盆子", "200g sugar 糖", "200ml apple cider vinegar 苹果醋"],
      "Macerate berries with sugar 24h refrigerated. Add vinegar, rest 2 days, strain and bottle.\n覆盆子与糖冷藏渍24小时,加醋静置2天后过滤装瓶。",
      "~400ml",
      "2 months refrigerated 冷藏2个月",
      "Refrigerate in sealed bottle 密封冷藏",
      "Great with soda or in low-ABV highballs.",
    ),
    mk(
      "Limoncello",
      "柠檬切罗利口酒",
      "liqueur",
      [
        "zest of 10 lemons 柠檬皮(只取黄色部分)",
        "500ml vodka or grain spirit 伏特加或食用酒精",
        "400ml simple syrup 单糖浆",
      ],
      "Infuse lemon zest in spirit 7-14 days in a sealed jar, shaking daily. Strain, mix with syrup, rest 1 week before serving.\n柠檬皮浸入烈酒密封7-14天,每天摇晃;过滤后与糖浆混合,静置1周风味更圆润。",
      "~900ml",
      "6 months+ refrigerated 冷藏6个月以上",
      "Freezer or refrigerator 冷冻/冷藏",
      "Serve ice-cold. Also great in a Limoncello Spritz.",
    ),
    mk(
      "Coffee Liqueur",
      "自制咖啡利口酒",
      "liqueur",
      [
        "250ml cold brew concentrate 冷萃咖啡浓缩液",
        "250ml vodka or aged rum 伏特加或陈年朗姆",
        "200g demerara sugar 德梅拉拉糖",
        "1/2 vanilla bean 香草荚(可选)",
      ],
      "Dissolve sugar in warm cold brew, cool, combine with spirit and vanilla. Rest 3-5 days, remove vanilla, bottle.\n糖溶入温热冷萃咖啡,放凉后与酒和香草荚混合,静置3-5天后取出香草装瓶。",
      "~650ml",
      "3 months+ 常温3个月以上",
      "Cool dark place 阴凉避光",
      "For Espresso Martini, White Russian. Less sweet than Kahlúa.",
    ),
    mk(
      "Orange Bitters",
      "自制橙味苦精",
      "bitters",
      [
        "zest of 4 oranges (dried) 干橙皮",
        "10g gentian root 龙胆根",
        "5g cardamom & coriander 小豆蔻与芫荽籽",
        "250ml high-proof spirit 高度烈酒(50%+)",
      ],
      "Combine all in a jar, infuse 2 weeks shaking daily, strain through coffee filter, bottle with dropper.\n所有材料入罐浸2周,每日摇晃,咖啡滤纸过滤后装滴瓶。",
      "~250ml",
      "1 year+ 常温1年以上",
      "Room temperature, dark bottle 常温避光",
      "Dash into Martinis and Old Fashioneds.",
    ),
    mk(
      "Milk-Washed Rum",
      "奶洗朗姆",
      "redistilled",
      [
        "500ml aged rum 陈年朗姆",
        "150ml whole milk 全脂牛奶",
        "60ml fresh lemon juice 鲜柠檬汁",
      ],
      "Pour rum + lemon into milk (not reverse), let curdle 1h, strain through coffee filter until clear.\n朗姆与柠檬汁倒入牛奶(顺序勿反),静置1小时凝乳,咖啡滤纸过滤至澄清。",
      "~550ml",
      "1 month refrigerated 冷藏1个月",
      "Refrigerate in sealed bottle 密封冷藏",
      "Silky texture, rounder flavor — clarified Milk Punch base.",
    ),
    mk(
      "Ginger Beer (Homebrew)",
      "自酿姜汁啤酒",
      "fermented",
      [
        "100g fresh ginger, grated 鲜姜蓉",
        "150g sugar 糖",
        "1L water 水",
        "juice of 1 lime 青柠汁",
        "1/4 tsp dry yeast 干酵母",
      ],
      "Dissolve sugar in warm water, add ginger, lime and yeast. Bottle in plastic, ferment 24-48h at room temp until firm, refrigerate.\n糖溶温水后加姜蓉、青柠汁和酵母,装塑料瓶常温发酵24-48小时至瓶身变硬,转冷藏。",
      "~1L",
      "1 week refrigerated 冷藏1周",
      "Refrigerate, open carefully 冷藏,小心开瓶泄压",
      "For Moscow Mule, Dark 'n' Stormy. Burp bottles to avoid overpressure!",
    ),
    mk(
      "Quick Sweet Vermouth",
      "快手甜味美思",
      "fortified",
      [
        "500ml dry red wine 干红葡萄酒",
        "100ml brandy 白兰地",
        "80g sugar (caramelized) 焦糖化砂糖",
        "5g wormwood & botanicals 苦艾草与香料(丁香/橙皮/肉桂)",
      ],
      "Simmer botanicals in a cup of wine 10 min, strain into remaining wine. Add caramel syrup and brandy, rest 2 days.\n香料在一杯酒中小火煮10分钟,滤入剩余酒液,加焦糖浆与白兰地,静置2天。",
      "~650ml",
      "1 month refrigerated 冷藏1个月",
      "Refrigerate after opening 开瓶后冷藏",
      "For Negroni & Manhattan experiments.",
    ),
  ];
}
