import { Bottle } from "./types";

/**
 * 内置酒款数据集:覆盖市面常见的烈酒、利口酒、苦精、味美思、开胃酒、
 * 起泡酒、葡萄酒、清酒烧酒、中式白酒、糖浆与软饮等 200+ 款。
 * 价格为中国电商/商超常见参考价(人民币),会随市场波动,仅供参考。
 */
export function buildDefaultBottles(): Bottle[] {
  const now = Date.now();
  let i = 0;
  const mk = (
    nameZh: string,
    nameEn: string,
    category: string,
    brand: string,
    origin: string,
    volume: string,
    abv: number,
    priceCny: number,
    notes = "",
    style = "",
  ): Bottle => ({
    id: `bottle-${i}`,
    nameZh,
    nameEn,
    category,
    style,
    brand,
    origin,
    volume,
    abv,
    priceCny,
    notes,
    builtin: true,
    flavorTags: [],
    story: "",
    styleDesc: "",
    rating: null,
    sortIndex: null,
    createdAt: now + i,
    updatedAt: now + i++,
  });

  return [
    // ============ 金酒 Gin ============
    mk("哥顿金酒", "Gordon's London Dry Gin", "金酒", "Gordon's", "英国", "700ml", 37.5, 75, "经典伦敦干金,入门性价比之选", "London Dry"),
    mk("必富达金酒", "Beefeater London Dry Gin", "金酒", "Beefeater", "英国", "700ml", 40, 110, "杜松子风味突出,金汤力常客", "London Dry"),
    mk("必富达24金酒", "Beefeater 24", "金酒", "Beefeater", "英国", "700ml", 45, 220, "含日本煎茶,风味更复杂", "London Dry"),
    mk("添加利金酒", "Tanqueray London Dry Gin", "金酒", "Tanqueray", "英国", "750ml", 43.1, 140, "四重蒸馏,口感干爽", "London Dry"),
    mk("添加利十号金酒", "Tanqueray No. Ten", "金酒", "Tanqueray", "英国", "700ml", 47.3, 320, "鲜柑橘蒸馏,高级马天尼首选", "London Dry"),
    mk("孟买蓝宝石金酒", "Bombay Sapphire", "金酒", "Bombay", "英国", "750ml", 40, 150, "十种植物香料,风味柔和", "London Dry"),
    mk("亨利爵士金酒", "Hendrick's Gin", "金酒", "Hendrick's", "苏格兰", "700ml", 41.4, 320, "黄瓜与玫瑰风味,适合G&T", "Contemporary"),
    mk("普利茅斯金酒", "Plymouth Gin", "金酒", "Plymouth", "英国", "700ml", 41.2, 280, "柔和微甜,历史悠久", "Plymouth"),
    mk("希普史密斯金酒", "Sipsmith London Dry Gin", "金酒", "Sipsmith", "英国", "700ml", 41.6, 300, "小批量铜壶蒸馏", "London Dry"),
    mk("猴子47金酒", "Monkey 47", "金酒", "Monkey 47", "德国", "500ml", 47, 420, "47种植物,黑森林名酒", "Contemporary"),
    mk("植物学家金酒", "The Botanist", "金酒", "The Botanist", "苏格兰", "700ml", 46, 380, "艾雷岛22种手采植物", "Contemporary"),
    mk("马翁金酒", "Gin Mare", "金酒", "Gin Mare", "西班牙", "700ml", 42.7, 380, "地中海风格,橄榄迷迭香", "Contemporary"),
    mk("罗库金酒", "Roku Gin", "金酒", "Suntory", "日本", "700ml", 43, 220, "六种日本植物,樱花柚子", "Contemporary"),
    mk("季之美金酒", "Ki No Bi Kyoto Dry Gin", "金酒", "Ki No Bi", "日本", "700ml", 45.7, 480, "京都精酿,玉露茶柚子", "Contemporary"),
    mk("老汤姆金酒", "Hayman's Old Tom Gin", "金酒", "Hayman's", "英国", "700ml", 41.4, 240, "微甜老汤姆,Tom Collins 经典", "Old Tom"),
    mk("黑刺李金酒", "Sipsmith Sloe Gin", "金酒", "Sipsmith", "英国", "500ml", 29, 280, "黑刺李浸渍,Sloe Gin Fizz", "Sloe Gin"),
    // ============ 朗姆 Rum ============
    mk("百加得白朗姆", "Bacardi Carta Blanca", "朗姆", "Bacardi", "波多黎各", "750ml", 40, 85, "轻盈白朗姆,大吉利基酒", "Spanish Style (Añejo)"),
    mk("百加得金朗姆", "Bacardi Carta Oro", "朗姆", "Bacardi", "波多黎各", "750ml", 40, 90, "轻度陈酿,古巴自由", "Spanish Style (Añejo)"),
    mk("百加得黑朗姆", "Bacardi Carta Negra", "朗姆", "Bacardi", "波多黎各", "750ml", 40, 100, "焦糖橡木,Dark'n'Stormy 可用", "Spanish Style (Añejo)"),
    mk("百加得151", "Bacardi 151", "朗姆", "Bacardi", "波多黎各", "750ml", 75.5, 200, "高度朗姆,漂浮点火用(已停产,存量有售)", "Overproof"),
    mk("哈瓦那俱乐部3年", "Havana Club 3 Años", "朗姆", "Havana Club", "古巴", "700ml", 40, 130, "古巴风格,莫吉托首选", "Spanish Style (Añejo)"),
    mk("哈瓦那俱乐部7年", "Havana Club 7 Años", "朗姆", "Havana Club", "古巴", "700ml", 40, 260, "陈年古巴朗姆,可纯饮", "Spanish Style (Añejo)"),
    mk("哈瓦那特级陈酿", "Havana Club Añejo Especial", "朗姆", "Havana Club", "古巴", "700ml", 40, 160, "金色朗姆,调酒通用", "Spanish Style (Añejo)"),
    mk("外交官精选朗姆", "Diplomático Reserva Exclusiva", "朗姆", "Diplomático", "委内瑞拉", "700ml", 40, 380, "甜润陈年朗姆,可纯饮", "Spanish Style (Añejo)"),
    mk("萨凯帕23朗姆", "Ron Zacapa 23", "朗姆", "Zacapa", "危地马拉", "700ml", 40, 480, "索莱拉陈酿,层次丰富", "Spanish Style (Añejo)"),
    mk("凯珊白朗姆", "Mount Gay Silver", "朗姆", "Mount Gay", "巴巴多斯", "700ml", 40, 150, "世界最古老朗姆酒厂之一", "Spanish Style (Añejo)"),
    mk("凯珊黑桶朗姆", "Mount Gay Black Barrel", "朗姆", "Mount Gay", "巴巴多斯", "700ml", 43, 300, "波本桶陈,香料感强", "Spanish Style (Añejo)"),
    mk("普雷森3星白朗姆", "Plantation 3 Stars", "朗姆", "Plantation", "加勒比", "700ml", 41.2, 160, "三岛调配,白朗姆标杆", "Spanish Style (Añejo)"),
    mk("普雷森原味黑朗姆", "Plantation Original Dark", "朗姆", "Plantation", "加勒比", "700ml", 40, 180, "浓郁黑朗姆,Mai Tai 好搭档", "Spanish Style (Añejo)"),
    mk("普雷森菠萝朗姆", "Plantation Stiggins' Fancy Pineapple", "朗姆", "Plantation", "加勒比", "700ml", 40, 320, "菠萝浸渍,提基酒神器", "Spanish Style (Añejo)"),
    mk("阿普尔顿庄园签名", "Appleton Estate Signature", "朗姆", "Appleton", "牙买加", "700ml", 40, 180, "牙买加壶式蒸馏,酯香明显", "English Style (Jamaican)"),
    mk("汉普登庄园朗姆", "Hampden Estate 8 Year", "朗姆", "Hampden", "牙买加", "700ml", 46, 520, "高酯牙买加funk代表", "Spanish Style (Añejo)"),
    mk("史密斯克罗斯朗姆", "Smith & Cross", "朗姆", "Smith & Cross", "牙买加", "700ml", 57, 380, "海军强度,提基与酸酒骨架", "English Style (Jamaican)"),
    mk("古斯林黑封朗姆", "Goslings Black Seal", "朗姆", "Goslings", "百慕大", "700ml", 40, 200, "Dark'n'Stormy 官方指定", "Black Rum"),
    mk("雷内夫高度白朗姆", "Wray & Nephew Overproof", "朗姆", "Wray & Nephew", "牙买加", "700ml", 63, 280, "高度白朗姆,牙买加国民酒", "Overproof"),
    mk("卡沙萨51", "Cachaça 51", "朗姆", "51", "巴西", "700ml", 39, 100, "巴西甘蔗酒,凯匹林纳必备", "Cachaça"),
    mk("雅琪卡沙萨", "Yaguara Cachaça Branca", "朗姆", "Yaguara", "巴西", "700ml", 41.5, 260, "精品卡沙萨,草本清新", "Cachaça"),
    // ============ 伏特加 Vodka ============
    mk("斯米诺红牌伏特加", "Smirnoff No.21 Vodka", "伏特加", "Smirnoff", "美国", "700ml", 40, 60, "全球销量最大伏特加之一", "Wheat"),
    mk("绝对伏特加", "Absolut Vodka", "伏特加", "Absolut", "瑞典", "750ml", 40, 100, "冬小麦酿造,口感纯净", "Wheat"),
    mk("绝对柠檬伏特加", "Absolut Citron", "伏特加", "Absolut", "瑞典", "700ml", 40, 110, "柠檬风味,大都会必备", "Flavored"),
    mk("灰雁伏特加", "Grey Goose Vodka", "伏特加", "Grey Goose", "法国", "750ml", 40, 330, "高端伏特加代表", "Grape"),
    mk("雪树伏特加", "Belvedere Vodka", "伏特加", "Belvedere", "波兰", "700ml", 40, 320, "黑麦酿造,细腻辛香", "Potato"),
    mk("坎特一号伏特加", "Ketel One Vodka", "伏特加", "Ketel One", "荷兰", "700ml", 40, 220, "铜壶蒸馏,酒吧常备", "Wheat"),
    mk("铁托手工伏特加", "Tito's Handmade Vodka", "伏特加", "Tito's", "美国", "700ml", 40, 180, "玉米酿造,无麸质"),
    mk("波兰野牛草伏特加", "Żubrówka Bison Grass", "伏特加", "Żubrówka", "波兰", "700ml", 37.5, 120, "野牛草风味,配苹果汁"),
    mk("俄国标准伏特加", "Russian Standard Original", "伏特加", "Russian Standard", "俄罗斯", "700ml", 40, 90, "经典俄式伏特加", "Wheat"),
    mk("水楢桶烧酎Haku", "Haku Vodka", "伏特加", "Suntory", "日本", "700ml", 40, 200, "日本米伏特加,柔和微甜", "Wheat"),
    // ============ 威士忌 Whisky ============
    mk("占边波本威士忌", "Jim Beam Bourbon", "威士忌", "Jim Beam", "美国", "750ml", 40, 90, "经典波本,适合调酒", "Bourbon"),
    mk("威凤凰波本威士忌", "Wild Turkey 101", "威士忌", "Wild Turkey", "美国", "700ml", 50.5, 160, "高度数,古典鸡尾酒骨架感强", "Bourbon"),
    mk("美格波本威士忌", "Maker's Mark", "威士忌", "Maker's Mark", "美国", "750ml", 45, 220, "小麦波本,柔甜圆润", "Bourbon"),
    mk("巴佛兰波本威士忌", "Buffalo Trace", "威士忌", "Buffalo Trace", "美国", "700ml", 45, 240, "均衡波本,老式鸡尾酒优选", "Bourbon"),
    mk("四玫瑰波本威士忌", "Four Roses Bourbon", "威士忌", "Four Roses", "美国", "700ml", 40, 150, "花香果香,入门友好", "Bourbon"),
    mk("伍德福德珍藏波本", "Woodford Reserve", "威士忌", "Woodford Reserve", "美国", "750ml", 43.2, 320, "肯塔基精酿,曼哈顿佳选", "Bourbon"),
    mk("杰克丹尼田纳西威士忌", "Jack Daniel's Old No.7", "威士忌", "Jack Daniel's", "美国", "700ml", 40, 130, "枫木炭过滤,Jack Coke", "Tennessee"),
    mk("布莱特黑麦威士忌", "Bulleit Rye", "威士忌", "Bulleit", "美国", "700ml", 45, 220, "黑麦辛香,曼哈顿首选", "Rye"),
    mk("瑞顿房黑麦威士忌", "Rittenhouse Rye 100 Proof", "威士忌", "Rittenhouse", "美国", "700ml", 50, 300, "保税黑麦,经典酒吧标配", "Rye"),
    mk("尊美醇爱尔兰威士忌", "Jameson Irish Whiskey", "威士忌", "Jameson", "爱尔兰", "700ml", 40, 130, "三次蒸馏,柔顺易饮", "Irish"),
    mk("布什米尔黑标", "Bushmills Black Bush", "威士忌", "Bushmills", "爱尔兰", "700ml", 40, 180, "雪莉桶调配爱尔兰威士忌", "Irish"),
    mk("格兰菲迪12年", "Glenfiddich 12", "威士忌", "Glenfiddich", "苏格兰", "700ml", 40, 280, "单一麦芽入门经典", "Scotch Single Malt"),
    mk("格兰威特12年", "The Glenlivet 12", "威士忌", "The Glenlivet", "苏格兰", "700ml", 40, 280, "花果香斯佩塞风格", "Scotch Single Malt"),
    mk("泰斯卡10年", "Talisker 10", "威士忌", "Talisker", "苏格兰", "700ml", 45.8, 380, "海盐胡椒,烟熏适中", "Scotch Single Malt"),
    mk("拉弗格10年", "Laphroaig 10", "威士忌", "Laphroaig", "苏格兰", "700ml", 40, 400, "重泥煤,Penicillin 点睛", "Islay Single Malt"),
    mk("波摩12年", "Bowmore 12", "威士忌", "Bowmore", "苏格兰", "700ml", 40, 350, "均衡泥煤,艾雷岛入门", "Islay Single Malt"),
    mk("芝华士12年", "Chivas Regal 12", "威士忌", "Chivas", "苏格兰", "700ml", 40, 180, "调和苏格兰,顺滑蜜甜", "Scotch Blended"),
    mk("尊尼获加黑牌", "Johnnie Walker Black Label", "威士忌", "Johnnie Walker", "苏格兰", "700ml", 40, 200, "12年调和,烟熏平衡", "Scotch Blended"),
    mk("猴肩膀调和麦芽", "Monkey Shoulder", "威士忌", "Monkey Shoulder", "苏格兰", "700ml", 40, 220, "三厂麦芽调和,专为调酒设计", "Scotch Blended"),
    mk("三得利角瓶", "Suntory Kakubin", "威士忌", "Suntory", "日本", "700ml", 40, 130, "日式高球标配"),
    mk("白州蒸馏所威士忌", "Hakushu Distiller's Reserve", "威士忌", "Suntory", "日本", "700ml", 43, 580, "森林青苹果,清爽日威", "Japanese"),
    mk("知多谷物威士忌", "Chita Single Grain", "威士忌", "Suntory", "日本", "700ml", 43, 400, "轻盈谷物,日式高球升级"),
    mk("加拿大俱乐部威士忌", "Canadian Club", "威士忌", "Canadian Club", "加拿大", "700ml", 40, 100, "轻盈加威,经典highball", "Canadian"),
    // ============ 龙舌兰 Agave ============
    mk("奥美加白龙舌兰", "Olmeca Blanco", "龙舌兰", "Olmeca", "墨西哥", "700ml", 38, 110, "入门级,玛格丽特常用", "Tequila Blanco"),
    mk("金快活银龙舌兰", "Jose Cuervo Especial Silver", "龙舌兰", "Jose Cuervo", "墨西哥", "750ml", 38, 130, "全球知名龙舌兰品牌", "Tequila Blanco"),
    mk("金快活传统银", "Jose Cuervo Tradicional Silver", "龙舌兰", "Jose Cuervo", "墨西哥", "700ml", 38, 220, "100%蓝色龙舌兰", "Tequila Blanco"),
    mk("1800银龙舌兰", "1800 Silver", "龙舌兰", "1800", "墨西哥", "700ml", 38, 240, "100%龙舌兰,顺滑均衡", "Tequila Blanco"),
    mk("唐胡里奥珍藏白", "Don Julio Blanco", "龙舌兰", "Don Julio", "墨西哥", "750ml", 38, 420, "100%蓝色龙舌兰,清新植物香", "Tequila Blanco"),
    mk("唐胡里奥微陈", "Don Julio Reposado", "龙舌兰", "Don Julio", "墨西哥", "750ml", 38, 480, "8个月桶陈,香草蜂蜜", "Tequila Reposado"),
    mk("培恩银樽", "Patrón Silver", "龙舌兰", "Patrón", "墨西哥", "750ml", 40, 450, "高端龙舌兰代表", "Tequila Blanco"),
    mk("奥乔白龙舌兰", "Tequila Ocho Plata", "龙舌兰", "Ocho", "墨西哥", "500ml", 40, 380, "单一庄园,风土表达", "Tequila Blanco"),
    mk("公牛屋银龙舌兰", "Espolòn Blanco", "龙舌兰", "Espolòn", "墨西哥", "750ml", 40, 220, "性价比100%龙舌兰,酒吧热门", "Tequila Blanco"),
    mk("维达梅斯卡尔", "Del Maguey Vida Mezcal", "龙舌兰", "Del Maguey", "墨西哥", "700ml", 42, 380, "入门梅斯卡尔,烟熏担当", "Mezcal Joven"),
    mk("阿玛拉斯梅斯卡尔", "Amarás Espadín", "龙舌兰", "Amarás", "墨西哥", "700ml", 41, 420, "清雅烟熏,Naked & Famous"),
    // ============ 白兰地 Brandy ============
    mk("轩尼诗VS干邑", "Hennessy V.S", "白兰地", "Hennessy", "法国", "700ml", 40, 320, "边车等干邑鸡尾酒基酒", "Cognac VS"),
    mk("马爹利VSOP", "Martell VSOP", "白兰地", "Martell", "法国", "700ml", 40, 420, "圆润果香干邑", "Cognac VSOP"),
    mk("人头马VSOP", "Rémy Martin VSOP", "白兰地", "Rémy Martin", "法国", "700ml", 40, 450, "香槟区葡萄,优雅平衡", "Cognac VSOP"),
    mk("圣雷米VSOP白兰地", "St-Rémy VSOP", "白兰地", "St-Rémy", "法国", "700ml", 40, 110, "法国葡萄白兰地,调酒性价比高", "Cognac VSOP"),
    mk("皮埃尔费朗琥珀干邑", "Pierre Ferrand Ambre", "白兰地", "Pierre Ferrand", "法国", "700ml", 40, 480, "边车专用级干邑"),
    mk("卡尔瓦多斯苹果白兰地", "Boulard Calvados VSOP", "白兰地", "Boulard", "法国", "700ml", 40, 300, "诺曼底苹果白兰地,Jack Rose", "Calvados"),
    mk("拉厄德皮斯科", "La Diablada Pisco", "白兰地", "La Diablada", "秘鲁", "700ml", 40, 300, "皮斯科酸酒基酒", "Pisco"),
    mk("卡佩尔皮斯科", "Pisco Capel", "白兰地", "Capel", "智利", "700ml", 35, 160, "智利皮斯科,入门之选", "Pisco"),
    mk("希腊麦塔莎5星", "Metaxa 5 Stars", "白兰地", "Metaxa", "希腊", "700ml", 38, 180, "希腊白兰地,微甜香料"),
    // ============ 利口酒 Liqueur ============
    mk("君度橙酒", "Cointreau", "利口酒", "Cointreau", "法国", "700ml", 40, 170, "橙皮利口酒标杆,玛格丽特/边车必备", "Orange Liqueur"),
    mk("柑曼怡", "Grand Marnier Cordon Rouge", "利口酒", "Grand Marnier", "法国", "700ml", 40, 280, "干邑基底橙酒,更浓郁", "Orange Liqueur"),
    mk("波士蓝橙利口酒", "Bols Blue Curaçao", "利口酒", "Bols", "荷兰", "700ml", 21, 90, "蓝色系鸡尾酒着色担当", "Orange Liqueur"),
    mk("波士白可可利口酒", "Bols Crème de Cacao White", "利口酒", "Bols", "荷兰", "700ml", 24, 100, "白可可,Grasshopper/Alexander"),
    mk("波士棕可可利口酒", "Bols Crème de Cacao Brown", "利口酒", "Bols", "荷兰", "700ml", 24, 100, "棕可可,巧克力风味"),
    mk("波士绿薄荷利口酒", "Bols Peppermint Green", "利口酒", "Bols", "荷兰", "700ml", 24, 100, "绿薄荷,Grasshopper"),
    mk("波士紫罗兰利口酒", "Bols Parfait Amour", "利口酒", "Bols", "荷兰", "700ml", 24, 110, "紫罗兰花香,Aviation 变体"),
    mk("金巴利", "Campari", "利口酒", "Campari", "意大利", "750ml", 25, 150, "苦味开胃酒,尼格罗尼核心"),
    mk("阿佩罗", "Aperol", "利口酒", "Aperol", "意大利", "700ml", 11, 130, "轻苦橙味,Aperol Spritz"),
    mk("咖啡利口酒", "Kahlúa Coffee Liqueur", "利口酒", "Kahlúa", "墨西哥", "700ml", 16, 130, "白俄罗斯/浓缩马天尼必备", "Coffee Liqueur"),
    mk("添万利咖啡利口酒", "Tia Maria", "利口酒", "Tia Maria", "意大利", "700ml", 20, 180, "咖啡利口酒,较Kahlúa更干", "Coffee Liqueur"),
    mk("圣杰曼接骨木花利口酒", "St-Germain", "利口酒", "St-Germain", "法国", "700ml", 20, 330, "花香典雅,提升酒感层次", "Floral Liqueur"),
    mk("绿查特酒", "Chartreuse Verte", "利口酒", "Chartreuse", "法国", "700ml", 55, 500, "130种草本,Last Word 关键", "Herbal Liqueur"),
    mk("黄查特酒", "Chartreuse Jaune", "利口酒", "Chartreuse", "法国", "700ml", 43, 480, "更甜更柔的查特", "Herbal Liqueur"),
    mk("玛拉斯奇诺樱桃酒", "Luxardo Maraschino", "利口酒", "Luxardo", "意大利", "700ml", 32, 260, "航空邮件/Last Word 常用", "Cherry Liqueur"),
    mk("希零樱桃利口酒", "Cherry Heering", "利口酒", "Heering", "丹麦", "700ml", 24, 260, "血与沙/新加坡司令", "Cherry Liqueur"),
    mk("迪莎萝娜杏仁酒", "Disaronno Amaretto", "利口酒", "Disaronno", "意大利", "700ml", 28, 160, "杏仁香甜,教父鸡尾酒", "Nut Liqueur"),
    mk("百利甜酒", "Baileys Irish Cream", "利口酒", "Baileys", "爱尔兰", "700ml", 17, 130, "奶油利口酒,甜品酒常客", "Cream Liqueur"),
    mk("野格利口酒", "Jägermeister", "利口酒", "Jägermeister", "德国", "700ml", 35, 130, "56种草本,野格炸弹"),
    mk("杜林标蜂蜜利口酒", "Drambuie", "利口酒", "Drambuie", "苏格兰", "700ml", 40, 300, "威士忌蜂蜜草本,Rusty Nail", "Herbal Liqueur"),
    mk("法勒南利口酒", "John D. Taylor's Velvet Falernum", "利口酒", "Velvet Falernum", "巴巴多斯", "750ml", 11, 200, "青柠丁香杏仁,提基必备"),
    mk("圣马力诺茴香酒", "Sambuca Molinari", "利口酒", "Molinari", "意大利", "700ml", 42, 180, "茴香利口酒,配咖啡豆", "Anise Liqueur"),
    mk("佩诺茴香酒", "Pernod Anise", "利口酒", "Pernod", "法国", "700ml", 40, 220, "茴香开胃,Sazerac 涮杯", "Anise Liqueur"),
    mk("苦艾酒(法国绿)", "La Fée Absinthe Parisienne", "利口酒", "La Fée", "法国", "700ml", 68, 480, "苦艾酒,Sazerac/死而复生2号", "Anise Liqueur"),
    mk("加利安奴香草利口酒", "Galliano L'Autentico", "利口酒", "Galliano", "意大利", "700ml", 42.3, 240, "香草茴香,Harvey Wallbanger", "Herbal Liqueur"),
    mk("弗兰吉利榛子利口酒", "Frangelico", "利口酒", "Frangelico", "意大利", "700ml", 20, 180, "榛子风味,甜品鸡尾酒", "Nut Liqueur"),
    mk("蜜多丽蜜瓜利口酒", "Midori Melon Liqueur", "利口酒", "Midori", "日本", "700ml", 20, 160, "蜜瓜绿,Japanese Slipper", "Fruit Liqueur"),
    mk("马利宝椰子朗姆", "Malibu Coconut Rum", "利口酒", "Malibu", "加勒比", "700ml", 21, 100, "椰子风味,Piña Colada 快捷方案"),
    mk("波士荔枝利口酒", "Bols Lychee", "利口酒", "Bols", "荷兰", "700ml", 17, 100, "荔枝马天尼", "Fruit Liqueur"),
    mk("迪凯堡水蜜桃利口酒", "De Kuyper Peachtree", "利口酒", "De Kuyper", "荷兰", "700ml", 20, 100, "蜜桃味,Fuzzy Navel/贝利尼替代", "Fruit Liqueur"),
    mk("夏朗德皮诺甜酒", "Pineau des Charentes", "利口酒", "多品牌", "法国", "750ml", 17, 200, "干邑加葡萄汁,餐前酒"),
    mk("黑加仑利口酒", "Lejay Crème de Cassis", "利口酒", "Lejay", "法国", "700ml", 20, 200, "Kir/Kir Royale 必备", "Fruit Liqueur"),
    mk("覆盆子利口酒", "Chambord Black Raspberry", "利口酒", "Chambord", "法国", "500ml", 16.5, 260, "法式莓果,French Martini", "Fruit Liqueur"),
    mk("紫罗兰利口酒", "Rothman & Winter Crème de Violette", "利口酒", "Rothman & Winter", "奥地利", "700ml", 20, 280, "Aviation 的天空蓝紫色来源", "Floral Liqueur"),
    mk("生姜利口酒", "Domaine de Canton Ginger", "利口酒", "Domaine de Canton", "法国", "700ml", 28, 320, "鲜姜干邑利口酒"),
    mk("意大利柠檬甜酒", "Limoncello di Capri", "利口酒", "多品牌", "意大利", "500ml", 30, 150, "餐后冰饮,柠檬糖浆感", "Fruit Liqueur"),
    mk("苏兹龙胆利口酒", "Suze", "利口酒", "Suze", "法国", "700ml", 15, 220, "龙胆苦,White Negroni"),
    mk("意大利苦味酒诺尼诺", "Amaro Nonino Quintessentia", "利口酒", "Nonino", "意大利", "700ml", 35, 420, "Paper Plane 指定", "Amaro"),
    mk("阿玛罗蒙特内罗", "Amaro Montenegro", "利口酒", "Montenegro", "意大利", "700ml", 23, 260, "柔和花果苦酒,入门Amaro", "Amaro"),
    mk("阿玛罗阿韦尔纳", "Amaro Averna", "利口酒", "Averna", "意大利", "700ml", 29, 260, "西西里可乐感苦酒,Black Manhattan", "Amaro"),
    mk("菲奈特布兰卡", "Fernet-Branca", "利口酒", "Fernet-Branca", "意大利", "700ml", 39, 260, "浓烈薄荷草本,调酒师握手酒", "Amaro"),
    mk("西娜尔洋蓟苦酒", "Cynar", "利口酒", "Cynar", "意大利", "700ml", 16.5, 220, "洋蓟风味,Cynar Negroni", "Amaro"),
    // ============ 苦精 Bitters ============
    mk("安高天娜苦精", "Angostura Aromatic Bitters", "苦精", "Angostura", "特立尼达", "200ml", 44.7, 120, "老式鸡尾酒灵魂,几滴即可", "Aromatic"),
    mk("安高天娜橙味苦精", "Angostura Orange Bitters", "苦精", "Angostura", "特立尼达", "100ml", 28, 90, "马天尼/威士忌酸提香", "Orange"),
    mk("北秀德苦精", "Peychaud's Bitters", "苦精", "Peychaud's", "美国", "148ml", 35, 140, "Sazerac 必备,茴香樱桃调", "Aromatic"),
    mk("里根橙味苦精6号", "Regans' Orange Bitters No.6", "苦精", "Regans'", "美国", "148ml", 45, 130, "经典橙味苦精", "Orange"),
    mk("费氏兄弟老式苦精", "Fee Brothers Old Fashioned Bitters", "苦精", "Fee Brothers", "美国", "150ml", 17.5, 110, "温和香料调"),
    mk("费氏兄弟西柚苦精", "Fee Brothers Grapefruit Bitters", "苦精", "Fee Brothers", "美国", "150ml", 17, 120, "西柚香,Paloma 提升"),
    mk("苦味真相巧克力苦精", "The Bitter Truth Chocolate Bitters", "苦精", "The Bitter Truth", "德国", "200ml", 44, 180, "巧克力调,配陈年烈酒", "Chocolate"),
    mk("苦味真相芹菜苦精", "The Bitter Truth Celery Bitters", "苦精", "The Bitter Truth", "德国", "200ml", 44, 180, "血腥玛丽/Gin 类点睛", "Celery"),
    mk("斯克拉普薰衣草苦精", "Scrappy's Lavender Bitters", "苦精", "Scrappy's", "美国", "148ml", 47.5, 200, "花香苦精,Aviation 变奏"),
    // ============ 味美思 Vermouth ============
    mk("马天尼干味美思", "Martini Extra Dry", "味美思", "Martini", "意大利", "1000ml", 15, 90, "干马天尼必备", "Dry Vermouth"),
    mk("马天尼红味美思", "Martini Rosso", "味美思", "Martini", "意大利", "1000ml", 15, 90, "尼格罗尼/曼哈顿用甜味美思", "Sweet Vermouth"),
    mk("马天尼白味美思", "Martini Bianco", "味美思", "Martini", "意大利", "1000ml", 15, 90, "微甜花香,加汤力直饮", "Blanc/Bianco"),
    mk("仙山露干味美思", "Cinzano Extra Dry", "味美思", "Cinzano", "意大利", "1000ml", 15, 85, "百年品牌,性价比之选", "Dry Vermouth"),
    mk("仙山露红味美思", "Cinzano Rosso", "味美思", "Cinzano", "意大利", "1000ml", 15, 85, "甜味美思,草本焦糖", "Sweet Vermouth"),
    mk("杜凌白味美思", "Dolin Blanc", "味美思", "Dolin", "法国", "750ml", 16, 160, "法式清雅,Vesper 变奏", "Blanc/Bianco"),
    mk("杜凌干味美思", "Dolin Dry", "味美思", "Dolin", "法国", "750ml", 17.5, 160, "干马天尼精品之选", "Dry Vermouth"),
    mk("杜凌红味美思", "Dolin Rouge", "味美思", "Dolin", "法国", "750ml", 16, 160, "轻盈红味美思", "Sweet Vermouth"),
    mk("潘脱蜜安蒂卡", "Carpano Antica Formula", "味美思", "Carpano", "意大利", "1000ml", 16.5, 380, "香草浓郁,顶级曼哈顿", "Sweet Vermouth"),
    mk("潘脱蜜潘趣", "Punt e Mes", "味美思", "Carpano", "意大利", "750ml", 16, 220, "半苦半甜,加强版尼格罗尼", "Sweet Vermouth"),
    mk("好奇美国佬", "Cocchi Americano", "味美思", "Cocchi", "意大利", "750ml", 16.5, 180, "Vesper 推荐,轻苦花香", "Quinquina"),
    mk("好奇都灵味美思", "Cocchi Storico Vermouth di Torino", "味美思", "Cocchi", "意大利", "750ml", 16, 260, "都灵传统配方,可可橙皮"),
    mk("利莱白利口酒", "Lillet Blanc", "味美思", "Lillet", "法国", "750ml", 17, 180, "波尔多加强酒,Vesper/20世纪", "Blanc/Bianco"),
    mk("利莱红利口酒", "Lillet Rouge", "味美思", "Lillet", "法国", "750ml", 17, 180, "红果香料版利莱", "Sweet Vermouth"),
    // ============ 开胃酒 Aperitif ============
    mk("菲诺雪莉酒", "Tio Pepe Fino Sherry", "开胃酒", "González Byass", "西班牙", "750ml", 15, 150, "极干雪莉,Sherry Cobbler"),
    mk("阿蒙提拉多雪莉", "Lustau Amontillado Sherry", "开胃酒", "Lustau", "西班牙", "750ml", 18.5, 220, "坚果氧化风,Adonis"),
    mk("佩德罗希梅内斯雪莉", "Lustau Pedro Ximénez Sherry", "开胃酒", "Lustau", "西班牙", "750ml", 17, 260, "极甜PX,葡萄干糖浆感"),
    mk("茶色波特酒", "Graham's 10 Year Tawny Port", "开胃酒", "Graham's", "葡萄牙", "750ml", 20, 320, "坚果焦糖,餐后或调酒"),
    mk("红宝石波特酒", "Fonseca Ruby Port", "开胃酒", "Fonseca", "葡萄牙", "750ml", 20, 180, "果香浓郁,Port Flip"),
    mk("杜本内红", "Dubonnet Rouge", "开胃酒", "Dubonnet", "法国", "750ml", 14.8, 180, "金鸡纳加强酒,英女王最爱"),
    // ============ 起泡酒 Sparkling ============
    mk("普罗塞克起泡酒", "Prosecco DOC", "起泡酒", "多品牌", "意大利", "750ml", 11, 100, "Spritz/含羞草基底", "Prosecco"),
    mk("卡瓦起泡酒", "Freixenet Cordon Negro Cava", "起泡酒", "Freixenet", "西班牙", "750ml", 11.5, 90, "西班牙传统法起泡", "Cava"),
    mk("香槟(无年份干型)", "Moët & Chandon Brut Impérial", "起泡酒", "Moët & Chandon", "法国", "750ml", 12, 380, "法式75/香槟鸡尾酒", "Champagne"),
    mk("兰布鲁斯科微泡", "Lambrusco Emilia", "起泡酒", "多品牌", "意大利", "750ml", 8, 80, "微甜红起泡"),
    // ============ 葡萄酒 Wine ============
    mk("干型雷司令白葡萄酒", "Dry Riesling", "葡萄酒", "多品牌", "德国", "750ml", 12, 120, "高酸白葡萄酒,Spritzer"),
    mk("赤霞珠红葡萄酒", "Cabernet Sauvignon", "葡萄酒", "多品牌", "智利", "750ml", 13.5, 100, "红酒桑格利亚基底"),
    mk("波尔多红葡萄酒", "Bordeaux Rouge", "葡萄酒", "多品牌", "法国", "750ml", 13, 150, "New York Sour 漂浮"),
    // ============ 清酒烧酒 Sake/Shochu ============
    mk("獭祭純米大吟醸45", "Dassai 45 Junmai Daiginjo", "清酒烧酒", "獭祭", "日本", "720ml", 16, 260, "花果香清酒,Saketini", "Junmai Daiginjo"),
    mk("月桂冠清酒", "Gekkeikan Sake", "清酒烧酒", "月桂冠", "日本", "750ml", 14.5, 80, "入门清酒,清酒高球", "Junmai"),
    mk("亦竹麦烧酒", "iichiko Mugi Shochu", "清酒烧酒", "iichiko", "日本", "720ml", 25, 130, "大麦烧酒,Chu-Hai 基底", "Mugi Shochu"),
    mk("镜月烧酒", "Kyoget Soju", "清酒烧酒", "镜月", "韩国", "700ml", 16.9, 40, "韩式烧酒,果味调酒", "Soju"),
    mk("真露烧酒", "Jinro Chamisul Soju", "清酒烧酒", "真露", "韩国", "360ml", 16.5, 15, "国民烧酒,Soju Bomb", "Soju"),
    mk("梅乃宿梅酒", "Umenoyado Umeshu", "清酒烧酒", "梅乃宿", "日本", "720ml", 12, 180, "梅酒,苏打或汤力兑饮", "Umeshu"),
    mk("choya梅酒", "Choya Umeshu", "清酒烧酒", "Choya", "日本", "750ml", 15, 100, "带梅子果实的经典梅酒", "Umeshu"),
    // ============ 中式白酒 Baijiu ============
    mk("汾酒青花20", "Fenjiu Qinghua 20", "中式白酒", "汾酒", "中国", "500ml", 53, 400, "清香型,较适合调酒", "Light Aroma 清香"),
    mk("红星二锅头", "Red Star Erguotou", "中式白酒", "红星", "中国", "500ml", 56, 30, "高度清香,白酒酸酒实验款", "Light Aroma 清香"),
    mk("五粮液", "Wuliangye", "中式白酒", "五粮液", "中国", "500ml", 52, 1000, "浓香型代表", "Strong Aroma 浓香"),
    mk("茅台迎宾酒", "Moutai Yingbin", "中式白酒", "茅台", "中国", "500ml", 43, 120, "酱香入门,酱香拿铁既视感", "Sauce Aroma 酱香"),
    mk("桂林三花酒", "Guilin Sanhua Jiu", "中式白酒", "三花", "中国", "480ml", 52, 40, "米香型,清雅易调", "Rice Aroma 米香"),
    // ============ 糖浆 Syrups ============
    mk("莫林原味糖浆", "Monin Pure Cane Syrup", "糖浆", "Monin", "法国", "700ml", 0, 60, "标准单糖浆", "Syrup"),
    mk("莫林红石榴糖浆", "Monin Grenadine", "糖浆", "Monin", "法国", "700ml", 0, 60, "Tequila Sunrise/Jack Rose", "Syrup"),
    mk("莫林杏仁糖浆", "Monin Orgeat", "糖浆", "Monin", "法国", "700ml", 0, 70, "Mai Tai 必备杏仁糖浆", "Syrup"),
    mk("莫林香草糖浆", "Monin Vanilla Syrup", "糖浆", "Monin", "法国", "700ml", 0, 60, "甜品向鸡尾酒", "Syrup"),
    mk("莫林百香果糖浆", "Monin Passion Fruit Syrup", "糖浆", "Monin", "法国", "700ml", 0, 65, "Pornstar Martini", "Syrup"),
    mk("蜂蜜糖浆(自制)", "Honey Syrup (Homemade)", "糖浆", "自制", "—", "500ml", 0, 25, "蜂蜜1:1热水,Bee's Knees/Penicillin", "Syrup"),
    mk("姜糖浆(自制)", "Ginger Syrup (Homemade)", "糖浆", "自制", "—", "500ml", 0, 20, "鲜姜煮糖水,Penicillin", "Syrup"),
    mk("德梅拉拉糖浆(自制)", "Demerara Syrup (Homemade)", "糖浆", "自制", "—", "500ml", 0, 15, "2:1粗糖浆,Old Fashioned", "Syrup"),
    mk("椰浆", "Coco López Cream of Coconut", "糖浆", "Coco López", "波多黎各", "425g", 0, 45, "Piña Colada 官方椰浆", "Cream/Foam"),
    mk("安佳淡奶油", "Anchor Whipping Cream", "糖浆", "Anchor", "新西兰", "250ml", 0, 15, "White Russian/Alexander", "Cream/Foam"),
    mk("蛋白(可用鹰嘴豆水替代)", "Egg White / Aquafaba", "糖浆", "—", "—", "—", 0, 2, "酸酒泡沫,素食可用鹰嘴豆水", "Cream/Foam"),
    // ============ 软饮 Soft Drinks ============
    mk("怡泉汤力水", "Schweppes Tonic Water", "软饮", "Schweppes", "英国", "330ml", 0, 6, "金汤力标配", "Tonic"),
    mk("芬味树汤力水", "Fever-Tree Indian Tonic", "软饮", "Fever-Tree", "英国", "200ml", 0, 12, "精品汤力,天然奎宁", "Tonic"),
    mk("芬味树姜汁啤酒", "Fever-Tree Ginger Beer", "软饮", "Fever-Tree", "英国", "200ml", 0, 12, "Moscow Mule/Dark'n'Stormy", "Ginger Beer"),
    mk("怡泉苏打水", "Schweppes Soda Water", "软饮", "Schweppes", "英国", "330ml", 0, 5, "高球/菲兹稀释", "Soda"),
    mk("圣佩黎洛气泡水", "S.Pellegrino Sparkling Water", "软饮", "S.Pellegrino", "意大利", "500ml", 0, 10, "餐配气泡水,也可调酒", "Sparkling Water"),
    mk("怡泉干姜水", "Schweppes Ginger Ale", "软饮", "Schweppes", "英国", "330ml", 0, 6, "Highball/Horse's Neck", "Ginger Ale"),
    mk("可口可乐", "Coca-Cola", "软饮", "Coca-Cola", "美国", "330ml", 0, 3.5, "自由古巴必备", "Cola"),
    mk("新奇士西柚汁", "Sunkist Grapefruit Juice", "软饮", "Sunkist", "美国", "1L", 0, 15, "Paloma/Greyhound", "Juice"),
    mk("蔓越莓汁", "Ocean Spray Cranberry Juice", "软饮", "Ocean Spray", "美国", "1L", 0, 25, "大都会/海风", "Juice"),
    mk("菠萝汁", "Del Monte Pineapple Juice", "软饮", "Del Monte", "美国", "1L", 0, 20, "Piña Colada/提基", "Juice"),
    mk("番茄汁", "Campbell's Tomato Juice", "软饮", "Campbell's", "美国", "1L", 0, 25, "血腥玛丽", "Juice"),
    // ============ 原材料 Raw Materials(中国电商参考价) ============
    // 糖类 Sugar & Sweetener
    mk("白砂糖", "White Sugar", "糖与甜味剂", "太古/舸禧", "中国", "1kg", 0, 8, "简单糖浆/油糖基础", "Refined Sugar"),
    mk("原蔗糖/红糖", "Demerara / Raw Sugar", "糖与甜味剂", "太古", "中国", "1kg", 0, 20, "德梅拉拉糖浆/老式", "Raw / Dark Sugar"),
    mk("冰糖", "Rock Sugar", "糖与甜味剂", "方家铺子", "中国", "1kg", 0, 12, "自制利口酒/浸渍", "Refined Sugar"),
    mk("蜂蜜", "Honey", "糖与甜味剂", "百花", "中国", "1kg", 0, 40, "蜂蜜糖浆/Bee's Knees", "Honey & Nectar"),
    mk("龙舌兰蜜", "Agave Nectar", "糖与甜味剂", "Naturel", "墨西哥", "500g", 0, 40, "Tommy's Margarita", "Molasses & Concentrate"),
    mk("枫糖浆", "Maple Syrup", "糖与甜味剂", "Ferns", "加拿大", "375ml", 0, 45, "枫糖老式", "Molasses & Concentrate"),
    // 水果柑橘 Fruit & Citrus
    mk("青柠", "Fresh Limes", "果蔬", "盒马", "中国", "500g", 0, 15, "鲜榨青柠汁约240ml/500g", "Citrus"),
    mk("柠檬", "Fresh Lemons", "果蔬", "盒马", "中国", "500g", 0, 8, "鲜榨柠檬汁约220ml/500g", "Citrus"),
    mk("橙子", "Fresh Oranges", "果蔬", "盒马", "中国", "500g", 0, 6, "鲜榨橙汁/橙皮装饰", "Citrus"),
    mk("西柚", "Fresh Grapefruit", "果蔬", "盒马", "中国", "500g", 0, 8, "Paloma/海盐狗", "Citrus"),
    mk("菠萝", "Fresh Pineapple", "果蔬", "盒马", "中国", "500g", 0, 6, "提基/菠萝糖浆", "Fresh Fruit"),
    mk("百香果", "Passion Fruit", "果蔬", "盒马", "中国", "500g", 0, 15, "百香果糖浆/Hurricane", "Fresh Fruit"),
    mk("树莓", "Raspberries", "果蔬", "盒马", "中国", "125g", 0, 15, "树莓糖浆/Clover Club", "Fresh Fruit"),
    mk("草莓", "Strawberries", "果蔬", "盒马", "中国", "500g", 0, 20, "草莓糖浆/浸渍", "Fresh Fruit"),
    mk("石榴", "Pomegranate", "果蔬", "盒马", "中国", "500g", 0, 10, "自制红石榴糖浆", "Fresh Fruit"),
    mk("黄瓜", "Cucumber", "果蔬", "盒马", "中国", "500g", 0, 4, "Pimm's Cup/浸渍金酒", "Fresh Vegetable"),
    mk("椰浆", "Coconut Cream", "坚果与谷物", "Kara", "印尼", "400ml", 0, 12, "Piña Colada", "Nut"),
    // 香料草本 Spice & Botanical
    mk("鲜姜", "Fresh Ginger", "香料与草本", "盒马", "中国", "500g", 0, 10, "姜汁糖浆/Penicillin", "Fresh Herb"),
    mk("肉桂", "Cinnamon Sticks", "香料与草本", "味好美", "中国", "250g", 0, 15, "肉桂糖浆/热红酒", "Dried Spice"),
    mk("丁香", "Cloves", "香料与草本", "味好美", "中国", "100g", 0, 8, "香料糖浆/热托蒂", "Dried Spice"),
    mk("八角", "Star Anise", "香料与草本", "味好美", "中国", "250g", 0, 15, "香料浸渍", "Dried Spice"),
    mk("豆蔻", "Cardamom", "香料与草本", "味好美", "印度", "100g", 0, 20, "法勒南/香料糖浆", "Dried Spice"),
    mk("香草荚", "Vanilla Beans", "香料与草本", "马达加斯加", "马达加斯加", "1根", 0, 15, "香草糖浆/自制利口酒", "Dried Spice"),
    mk("多香果", "Allspice Berries", "香料与草本", "味好美", "牙买加", "100g", 0, 12, "多香果利口酒", "Dried Spice"),
    mk("杜松子", "Juniper Berries", "香料与草本", "淘宝药材铺", "中国", "100g", 0, 15, "自制金酒浸渍", "Dried Spice"),
    mk("薄荷", "Fresh Mint", "香料与草本", "盒马", "中国", "100g", 0, 8, "Mojito/Julep 装饰", "Fresh Herb"),
    mk("迷迭香", "Rosemary", "香料与草本", "盒马", "中国", "100g", 0, 10, "迷迭香糖浆/装饰", "Fresh Herb"),
    mk("香茅", "Lemongrass", "香料与草本", "盒马", "中国", "250g", 0, 10, "东南亚风味糖浆", "Fresh Herb"),
    mk("龙胆根", "Gentian Root", "香料与草本", "淘宝药材铺", "中国", "100g", 0, 30, "自制苦精/阿玛罗", "Bittering Botanical"),
    mk("苦艾草", "Wormwood", "香料与草本", "淘宝药材铺", "中国", "100g", 0, 20, "自制味美思", "Bittering Botanical"),
    // 坚果茶咖 Nut / Tea / Coffee
    mk("杏仁", "Almonds", "坚果与谷物", "楼兰蜜语", "中国", "500g", 0, 35, "自制Orgeat杏仁糖浆", "Nut"),
    mk("伯爵茶", "Earl Grey Tea", "茶咖与可可", "川宁", "英国", "100g", 0, 40, "伯爵茶浸渍金酒", "Tea"),
    mk("绿茶", "Green Tea", "茶咖与可可", "狮峰", "中国", "100g", 0, 50, "冷泡茶/茶酒", "Tea"),
    mk("咖啡豆", "Coffee Beans", "茶咖与可可", "Manner", "中国", "500g", 0, 60, "冷萃/咖啡利口酒", "Coffee"),
    mk("可可碎", "Cacao Nibs", "茶咖与可可", "可可琳纳", "中国", "250g", 0, 30, "可可浸渍/巧克力苦精", "Cacao"),
    // 乳蛋 Dairy & Egg
    mk("全脂牛奶", "Whole Milk", "乳蛋", "光明", "中国", "1L", 0, 14, "奶洗澄清", "Milk / Cream"),
    mk("淡奶油", "Heavy Cream", "乳蛋", "安佳", "新西兰", "500ml", 0, 25, "白俄罗斯/爱尔兰咖啡", "Milk / Cream"),
    mk("鸡蛋", "Eggs", "乳蛋", "德青源", "中国", "10枚", 0, 12, "蛋白酸酒/菲兹", "Egg"),
    // 酸类添加剂 Acid & Additive
    mk("柠檬酸", "Citric Acid", "酸类与添加剂", "食品级", "中国", "500g", 0, 15, "澄清酸/超级果汁", "Powdered Acid"),
    mk("苹果酸", "Malic Acid", "酸类与添加剂", "食品级", "中国", "500g", 0, 30, "苹果风味酸化", "Powdered Acid"),
    mk("酒石酸", "Tartaric Acid", "酸类与添加剂", "食品级", "中国", "500g", 0, 40, "葡萄风味酸化", "Powdered Acid"),
    mk("食盐", "Salt", "酸类与添加剂", "中盐", "中国", "1kg", 0, 4, "盐边/盐溶液", "Salt & Mineral"),
    mk("苹果醋", "Apple Cider Vinegar", "酸类与添加剂", "海天", "中国", "500ml", 0, 10, "果醋饮 Shrub", "Vinegar"),
    mk("酵母", "Brewing Yeast", "酸类与添加剂", "安琪", "中国", "50g", 0, 15, "自酿姜汁啤酒", "Texture / Clarifier"),
    mk("橙花水", "Orange Flower Water", "花卉", "Cortas", "黎巴嫩", "200ml", 0, 30, "Ramos Gin Fizz", "Floral Water"),
    mk("玫瑰水", "Rose Water", "花卉", "Cortas", "黎巴嫩", "200ml", 0, 20, "花香调酒", "Floral Water"),
    // ============ 其他 Others ============
    mk("君度黑标(君度与干邑)", "Cointreau Noir", "其他", "Cointreau", "法国", "700ml", 40, 300, "君度+人头马干邑"),
    mk("绿茶(冷泡)", "Cold Brew Green Tea", "其他", "自制", "—", "1L", 0, 5, "日式Highball变奏/茶酒"),
    mk("浓缩咖啡", "Espresso", "其他", "现做", "—", "30ml", 0, 5, "Espresso Martini 必备"),
  ];
}
